[package]
name = "akiv"
version = "0.1.0"
authors = ["sergio garcia <sergio.garcia@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
chrono = "0.4"
parse_duration = "2.1.1"
rusqlite = {version = "0.25.1", features=["chrono"]}
directories = "3.0.2"
anyhow = "1.0.40"